Use zookeeper 3.8.1 for php > 8.0

diff --git a/install-php-extensions b/install-php-extensions
--- a/install-php-extensions
+++ b/install-php-extensions
@@ -3665,7 +3665,7 @@ installRemoteModule() {
 			;;
 		zookeeper)
 			if test -z "$installRemoteModule_version"; then
-				if test $PHP_MAJMIN_VERSION -le 506; then
+				if test $PHP_MAJMIN_VERSION -le 700; then
 					installRemoteModule_version=0.5.0
 				else
 					installRemoteModule_version=alpha
@@ -3678,12 +3678,16 @@ installRemoteModule() {
 						if test $(compareVersions "$installRemoteModule_version" 1.0.0) -lt 0; then
 							installRemoteModule_src="$(getPackageSource http://archive.apache.org/dist/zookeeper/zookeeper-3.5.9/apache-zookeeper-3.5.9.tar.gz)"
 						else
-							installRemoteModule_tmp="$(curl -sSLf https://downloads.apache.org/zookeeper/stable | sed -E 's/["<>]/\n/g' | grep -E '^(apache-)?zookeeper-[0-9]+\.[0-9]+\.[0-9]+\.(tar\.gz|tgz)$' | head -n1)"
-							if test -z "$installRemoteModule_tmp"; then
-								echo 'Failed to detect the zookeeper library URL' >&2
-								exit 1
-							fi
-							installRemoteModule_src="$(getPackageSource https://downloads.apache.org/zookeeper/stable/$installRemoteModule_tmp)"
+                            if test $PHP_MAJMIN_VERSION -ge 801; then
+							    installRemoteModule_src="$(getPackageSource http://archive.apache.org/dist/zookeeper/zookeeper-3.8.1/apache-zookeeper-3.8.1.tar.gz)"
+                            else
+                                installRemoteModule_tmp="$(curl -sSLf https://downloads.apache.org/zookeeper/stable | sed -E 's/["<>]/\n/g' | grep -E '^(apache-)?zookeeper-[0-9]+\.[0-9]+\.[0-9]+\.(tar\.gz|tgz)$' | head -n1)"
+                                if test -z "$installRemoteModule_tmp"; then
+                                    echo 'Failed to detect the zookeeper library URL' >&2
+                                    exit 1
+                                fi
+							    installRemoteModule_src="$(getPackageSource https://downloads.apache.org/zookeeper/stable/$installRemoteModule_tmp)"
+                            fi
 						fi
 						cd -- "$installRemoteModule_src"
 						if test -d ~/.m2; then
